; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = ./AstroEQ
include_dir = ./AstroEQ

[env]
platform = atmelavr
platform_packages =
  ; use GCC AVR 5.4.0+
  toolchain-atmelavr@<1.70300.0
extra_scripts = platformio_hooks.py
build_unflags = 
	-Os
	-std=gnu11
	-flto
	-fno-fat-lto-objects
build_flags = 
	-O2
	-std=gnu99
	-DNDEBUG
	-mrelax
	-funsigned-bitfields
	-fpack-struct
	-fshort-enums
	-Wl,--gc-sections

[env:ATmega162]
board = ATmega162

[env:Mega1280]
board = megaatmega1280

[env:Mega2560]
board = megaatmega2560

[env:Ramps14]
board = megaatmega2560
build_flags = -DPIN_MAP_MKS_GEN_L
